### ISSUE TITLE
only supports OpenSSL 1.1.1+,

### ISSUE THREAD

**Issue by minidevbd** [nuwandda/photo-enhancer#1]
I'm installed openssl version 3.1.1 but still this error in below.

Traceback (most recent call last):
  File "enhance_image.py", line 4, in <module>
    from torchvision.transforms import Resize, CenterCrop, ToTensor, Normalize
  File "C:\Python37\lib\site-packages\torchvision\__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "C:\Python37\lib\site-packages\torchvision\datasets\__init__.py", line 1, in <module>
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "C:\Python37\lib\site-packages\torchvision\datasets\_optical_flow.py", line 12, in <module>
    from .utils import _read_pfm, verify_str_arg
  File "C:\Python37\lib\site-packages\torchvision\datasets\utils.py", line 22, in <module>
    import requests
  File "C:\Python37\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Python37\lib\site-packages\urllib3\__init__.py", line 42, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.1.0i  14 Aug 2018'. See: https://github.com/urllib3/urllib3/issues/2168

**Comment by nuwandda** [comment]
The reason why the error message mentioned OpenSSL 1.1.1+ and LibreSSL 2.8.3 is that urllib3 v2.0 (the version you've installed) requires OpenSSL 1.1.1+ to work properly, as it relies on some new features of OpenSSL 1.1.1.

You can try to install a newer version of OpenSSL or you can downgrade the version of urllib using `pip install 'urllib3<2.0'`.
